### ISSUE TITLE
OneDrive: File permissions

### ISSUE THREAD

**Issue by gmatev** [alcionai/corso-roadmap#13]
Backup and restore original permissions for a OneDrive file

When feature is introduced it needs to support the full set of currently available flows:

Backup granularity (e.g. full service, selective by user, etc)
Backup listing
Restore granularity
Restore option (e.g. in-place, new location, etc)
CLI support for new item types and above options

**Comment by bchex** [comment]
@vkamra this is a dependency for Ark Preview. In which upcoming Corso cycle will this be included?

**Comment by gmatev** [comment]
@vkamra @meain is there anything outstanding for this issue or it can be closed?

**Comment by meain** [comment]
https://github.com/alcionai/corso/issues/1774 and https://github.com/alcionai/corso/issues/2028 are tracking this. There is still a bit more work pending here.

**Comment by meain** [comment]
OneDrive permissions backup/restore has landed in main, thought with it disable by default. We can close this now or should we keep it open until we make it default?
